listenAddress: 0.0.0.0      # Listen address for metrics endpoint
listenPort: 9345            # Listen port for metrics endpoint
computeInterval: 168h       # Interval between 2 computes
validityCheckIntervals:
- 1h
- 168h
- 672h
labelKeys:
- tenant
servers:
  - labelValues:                                                   # Added in metric label
    - my_tenant                                             
    alertUrl: https://vmalert.cluster.local.                        # Endpoint to get alerts
    selectUrl: https://vm.cluster.local./select/000/prometheus      # Endpoint to validate metrics
